import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [session, setSession] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Take a Break</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session ? (
          <div>
            <div>
              <button>2 minutes</button>
              <button>3 minutes</button>
              <button>5 minutes</button>
            </div>
            <button onClick={() => setSession(true)}>Start Session</button>
          </div>
        ) : (
          // Let the timer run
          // When the timer is up, set the session to false

          <div>Timer Occur Here</div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
