import React from "react";
import Head from "next/head";
import Image from "next/image";
import useCountDown from "react-countdown-hook";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const interval = 1000;

function formatTime(seconds) {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}:${remainingSeconds < 10 ? "0" : ""}${remainingSeconds}`;
}

export default function Home() {
  const [session, setSession] = useState(false);
  const [initialTime, setInitialTime] = useState(2 * 60 * 1000);
  const [timeLeft, { start, pause, resume, reset }] = useCountDown(initialTime, interval);

  const restart = React.useCallback((newTime) => start(newTime), []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Take a Break</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session ? (
          <div>
            <div>
              <button onClick={() => setInitialTime(2 * 60 * 1000)}>2 minutes</button>
              <button onClick={() => setInitialTime(3 * 60 * 1000)}>3 minutes</button>
              <button onClick={() => setInitialTime(5 * 60 * 1000)}>5 minutes</button>
            </div>
            <button
              onClick={() => {
                setSession(true);
                start();
              }}
            >
              Start Session
            </button>
          </div>
        ) : (
          // Let the timer run
          // When the timer is up, set the session to false
          <div>
            <p>Time left: {formatTime(timeLeft / 1000)}</p>

            <button onClick={() => restart(initialTime)}>Restart</button>

            <button
              onClick={() => {
                setSession(false);
              }}
            >
              End Session
            </button>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
